spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: wlalsdlqslek!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ?? ??? create / create-drop / update ? ??
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug